import { Component, OnDestroy } from '@angular/core';
import { LocalDate, LocalTime } from 'js-joda';
import { Ticker } from './services/ticker.model';
import { DataService } from './backend/data.service';



@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnDestroy {


  day_name: any = '';
  month_name: any = '';
  day_number: any = '';
  year_name: any = '';
  time: any = '';
  tickers: Ticker[] = [];
  intervalHandle: any;

  constructor(private ds: DataService) {


    this.intervalHandle = setInterval(() => {
      const day = LocalDate.now();
      const time = LocalTime.now();
      this.day_name = day.dayOfWeek();
      this.month_name = day.month();
      this.day_number = day.dayOfMonth();
      this.year_name = day.year();
      this.time = time.toString().split('.')[0];


      if (this.tickers.length === 0) {
        this.tickers = this.loadTickers();
      }

    }, 1000);

    this.tickers = this.loadTickers();


  }


  ngOnDestroy(): void {
    clearInterval(this.intervalHandle);
  }

  loadRooms() {
    this.ds.getRooms().subscribe(rooms => {
      console.log(rooms);
    });
  }


  loadTickers() {
    return [
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 202, Mr Ben is running out of deposited credit' },
      { type: 0, title: 'Low Credit', message: 'Custmer in room 201, Mr King is running out of deposited credit' },
      { type: 1, title: 'Low Inventry', message: 'The inventry is very low, please reorder' },
      { type: 2, title: 'No Connection', message: 'No Internet Connection in Room 505' },
      { type: 3, title: 'House Keeping', message: 'Room 305, is very dirty' },
      { type: 4, title: 'No Stock', message: 'Stock Level is very low' }
    ];
  }



}
